# Generated by Django 4.0.6 on 2022-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_newuser_age_alter_newuser_body_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='score',
            field=models.FloatField(default=0, verbose_name='总评'),
        ),
    ]
