# Generated by Django 4.0.6 on 2022-07-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_body_weight_newuser_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='position',
            field=models.CharField(choices=[['0', '前锋'], ['1', '左边锋'], ['2', '右边锋'], ['3', '前腰'], ['4', '中前卫'], ['5', '中后卫'], ['6', '左后卫'], ['7', '右后卫'], ['8', '门将']], max_length=32, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='sex',
            field=models.CharField(choices=[['0', '女'], ['1', '男']], max_length=32, null=True, verbose_name='性别'),
        ),
    ]
