# Generated by Django 4.0.6 on 2022-07-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_newuser_position_alter_newuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='stature',
            field=models.FloatField(null=True, verbose_name='身高'),
        ),
    ]
