# Generated by Django 4.0.6 on 2022-07-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_newuser_stature'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
