# Generated by Django 4.0.6 on 2022-07-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatar', verbose_name='头像'),
        ),
    ]
