# Generated by Django 4.0.6 on 2022-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_newuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='body',
            field=models.FloatField(default=0, verbose_name='身体'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='control',
            field=models.FloatField(default=0, verbose_name='盘带'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='defend',
            field=models.FloatField(default=0, verbose_name='防守'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='hotshot',
            field=models.FloatField(default=0, verbose_name='射门'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='pass_football',
            field=models.FloatField(default=0, verbose_name='传球'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='speed',
            field=models.FloatField(default=0, verbose_name='速度'),
        ),
    ]
