# Generated by Django 4.0.6 on 2022-09-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_newuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
