# Generated by Django 4.1.2 on 2022-10-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_notice"),
    ]

    operations = [
        migrations.DeleteModel(name="Notice",),
    ]
